config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :follows, only: ['index', 'create', 'destroy']
  resources :profiles, only: ['show']
  get 'home/timeline'
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
  }

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friend, :class_name=> "User"

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

  def validate_relationship
    current_user = User.find(follower_id)
    if current_user.following?(followed_id)
      errors.add(:followed_id, "user id is already followed")
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tweets, dependent: :destroy
  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :relationships, source: "follower_id"
  has_and_belongs_to_many :followers, class_name: "User", foreign_key: "followed_id", join_table: "relationships", association_foreign_key: "follower_id"
  has_and_belongs_to_many :following, class_name: "User", foreign_key: "follower_id", join_table: "relationships", association_foreign_key: "followed_id"

  validates :email, :first_name, :last_name, :username, presence: true
  validates :email, :username, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end

  def follow(other_user)
    following << other_user unless following?(other_user)
  end

  def unfollow(other_user)
    following.destroy(User.find(other_user.id))
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def send_email
    UserMailer.welcome_email(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  include ApplicationHelper
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :get_unfollowed_users, only: [:index]
  def index

  end

  def create
    @other_user = User.find(params[:id])
    if current_user.follow(@other_user)
      flash[:notice] = "Followed '@#{@other_user.username}' successfully"
    else
      flash[:error] = "Follow failed"
    end
    redirect_to root_url
  end

  def destroy
    @other_user = User.find(params[:id])
    if current_user.unfollow(@other_user)
      flash[:notice] = "Unfollowed '@#{@other_user.username}' successfully"
    else
      flash[:error] = "Unfollowed failed"
    end
    redirect_to root_url
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
      if @friendship.save
        flash[:notice] = "Added friend"
        redirect_to root_url
      else
        flash[:error] = "Error occured when adding friend."
        redirect_to root_url
      end
    end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
      if @friendship.destroy
        flash[:notice] = "successfully deleted a friend"
        redirect_to root_url
      else
        flash[:notice] = "Error occured when deleting a friend"
        redirect_to root_url
      end
  end

  def show
    @users = current_user
    
  end













end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_action :get_unfollowed_users, only: [:timeline]

  def index
    if user_signed_in?
      redirect_to home_timeline_path
    end
  end

  def timeline
    ids = current_user.following.ids << current_user.id
    @tweet = Tweet.new
    @tweets = Tweet.joins(:user).where(user_id: ids).order(created_at: :desc)
    @users = @unfollowed_users.limit(5).shuffle
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:update, :destroy]
  def index
  end

  def show
  end

  def new
  end

  def create
    @tweet = Tweet.new(tweet_params.merge(user_id: current_user.id))

    if @tweet.save
      redirect_to home_timeline_path, notice: 'Tweet was successfully created.'
    else
      redirect_to home_timeline_path, notice: 'Tweet was not created.'
    end
  end

  def edit
  end

  def update
  end

  def destroy
#  @tweet = Tweet.new(tweet_params.merge(user_id: current_user.id))
    @tweet.destroy
      redirect_to home_timeline_path, notice: 'tweet was successfully deleted'

  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    User
  end

  def get_unfollowed_users
    ids = current_user.following.ids << current_user.id
    @unfollowed_users = User.where.not(id: ids)
  end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar-default
  .container-fluid
    .navbar-header
      = link_to "Twitter Clone", root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav
          %li.nav-item
            = link_to "Home", root_path
          %li.nav-item
            = link_to "Global Feed", root_path
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.full_name
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to 'Edit Profile', edit_user_registration_path
              %li
                = link_to 'Log out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TwitterClone
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container{style: 'margin-top:5px'}
      - if notice
        %p.alert.alert-success
          = notice
      - if alert
        %p.alert.alert-danger
          = alert
      = yield

app/views/shared/_tweets.html.haml
- tweets.each do |t|
  .panel.panel-info
    .panel-heading
      %h2.panel-title{style: 'font-weight:bold !important;'}= t.user.full_name
      %span{style: 'color:grey !important'}
      = link_to "@#{t.user.username}", profile_path(t.user), style: 'text-decoration: none'
      - unless current_user != t.user
        = button_to 'Delete', t, :method => :delete, :data => { :confirm => 'Are you sure want to delete tweet?' }, class: "btn btn-xs btn-secondary"
    .panel-body
      = t.content
    .panel-footer
      = "#{time_ago_in_words(t.created_at)} ago"

app/views/shared/_user-details.html.haml
.panel.panel-primary
  .panel-heading
    %h2.panel-title{style: 'font-weight:bold !important;'} Profile
  .panel-body
    %p{style: 'font-weight:bold'}= user.full_name
    = "@#{user.username}"
    - unless user == current_user
      - if current_user.following?(user)
        = button_to 'Unfollow', follow_path(id: user.id), method: :delete, class: 'btn btn-xs btn-secondary pull-right'
      - else
        = button_to 'Follow', follows_path(id: user.id), method: :create, class: 'btn btn-xs btn-secondary pull-right'
  %ul.list-group
    %li.list-group-item
      = "Tweets: #{user.tweets.count}"
    %li.list-group-item
      = "Following: #{user.following.count}"
    %li.list-group-item
      = "Followers: #{user.followers.count}"
  - if user == current_user
    .panel-footer{style: 'text-align:center !important;'}
      = link_to 'Log out', destroy_user_session_path, method: :delete