config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :follows, only: ['index', 'create', 'destroy']
  resources :profiles, only: ['show']
  get 'home/timeline'
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
  }

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_action :get_unfollowed_users, only: [:timeline]

  def index
    if user_signed_in?
      redirect_to home_timeline_path
    end
  end

  def timeline
    ids = current_user.following.ids << current_user.id
    @tweet = Tweet.new
    @tweets = Tweet.joins(:user).where(user_id: ids).order(created_at: :desc)
    @users = @unfollowed_users.limit(5).shuffle
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.container
  .jumbotron
    %h1 Hello World
    %p This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
    .row
      .col-md-3
        = button_to "Sign up", new_user_registration_path, class: 'btn btn-lg btn-primary', method: :get
      .col-md-3
        = button_to "Sign in", new_user_session_path, class: 'btn btn-lg btn-danger', method: :get

app/views/home/timeline.html.haml
.container
  .row
    .col-md-3
      = render partial: "shared/user-details", locals: { user: current_user }
      .panel.panel-info
        .panel-heading
          %h2.panel-title{style: 'font-weight:bold !important'} Discover Users
        %ul.list-group
          - @users.each do |user|
            - unless user.id == current_user.id
              %li.list-group-item
                .row
                  .col-md-6
                    = user.full_name
                  .col-md-6
                    - if current_user.following?(user)
                      = button_to 'Unfollow', follow_path(id: user.id), method: :delete, class: 'btn btn-xs btn-secondary pull-right'
                    - else
                      = button_to 'Follow', follows_path(id: user.id), method: :create, class: 'btn btn-xs btn-secondary pull-right'
        .panel-footer
          = link_to 'See more', follows_path
    .col-md-9
      .tweet-form
        = form_for @tweet, :url => tweets_path do |f|
          .form-group
            = f.text_area :content, class: 'form-control', placeholder: "What's on your mind", :cols => 5, :rows => 5
          .form-group
            = f.submit 'Tweet', class: 'btn btn-secondary'

      .tweets-container
        = render partial: "shared/tweets", locals: { tweets: @tweets }